name: JAM light theme
baseurl: /JAM_theme_light
permalink: none
highlighter: true
prose:
  rooturl: '_posts'
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "Layout"
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Julkaistu"
          value: true
      - name: "category"
        field:
          element: "text"
          label: "Kategoria"
          value: ""
      - name: "subcategory"
        field:
          element: "text"
          label: "Alikategoria"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Otsikko"
          value: ""
      - name: "description"
        field:
          element: "text"
          label: "Kuvaus"
          value: ""